name: CD


on:
  push:
    branches:
     - main


jobs:
  docs:
    name: Deploy API Documentation
    runs-on: ubuntu-latest


  steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}

      - name: Check Python version
        run: python --version


      - name: Install dependencies
        run: python -m pip install myst-parser numpy numpydoc sphinx sphinx-book-theme

      - name: Build API documentation
        run: |
          sphinx-apidoc -Mfeo docs/source mycosmo
          sphinx-build docs/source docs/build

      - name: Deploy API documentation
        uses: peaceiris/actions-gh-pages@v3.5.9
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: docs/build
