name: CD

on:
  push:
    branches:
     - main

jobs:
  docs:
    name: Deploy API Documentation
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python 3.12
        uses: actions/setup-python@v5
        with:
          python-version: 3.12

      - name: Check Python version
        run: python --version

      - name: Install dependencies
        run: python -m pip install ".[docs]"

      - name: Build API documentation
        run: |
          sphinx-apidoc -Mfeo docs/source src/glass_cannon
          sphinx-build docs/source docs/build

      - name: Deploy API documentation
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: docs/build
