name: CI

on:
  pull_request:
    branches:
     - main


jobs:
  test-full:
    name: Run CI Tests
    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest]
        python-version: ["3.13"]

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}

      - name: Check Python version
        run: python --version

      - name: Install dependencies
        run: |
          python -m pip install git+https://github.com/glass-dev/glass.git
          python -m pip install numpy pytest glass.ext.camb camb cosmology.compat.camb jax

      - name: Run unit tests
        run: python -m pytest --verbose test_glass_cannon